// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViewPersonal.Server.Data;

#nullable disable

namespace ViewPersonal.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("ViewPersonal.Server.Models.AppVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Versions");
                });

            modelBuilder.Entity("ViewPersonal.Server.Models.VersionOsDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppVersionId");

                    b.ToTable("VersionOsDetails");
                });

            modelBuilder.Entity("ViewPersonal.Server.Models.VersionOsDetails", b =>
                {
                    b.HasOne("ViewPersonal.Server.Models.AppVersion", "AppVersion")
                        .WithMany("OsDetails")
                        .HasForeignKey("AppVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppVersion");
                });

            modelBuilder.Entity("ViewPersonal.Server.Models.AppVersion", b =>
                {
                    b.Navigation("OsDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
